TRUNCATE TABLE ACTIONS RESTART IDENTITY CASCADE;
TRUNCATE TABLE CONDITIONS RESTART IDENTITY CASCADE;
TRUNCATE TABLE scenario_conditions RESTART IDENTITY CASCADE;
TRUNCATE TABLE scenario_actions RESTART IDENTITY CASCADE;
TRUNCATE TABLE scenarios RESTART IDENTITY CASCADE;
TRUNCATE TABLE sensors RESTART IDENTITY CASCADE;