spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    #url=jdbc:postgresql://localhost:5432/telemetry_analyzer
    url: jdbc:postgresql://192.168.0.45:5432/shop_db
    username: postgres
    #password=postgres
    password: password

server:
  port: 0